Merge 84:221 from trunk

diff --git a/branches/simple_http_parsing/configure b/branches/simple_http_parsing/configure
--- a/branches/simple_http_parsing/configure
+++ b/branches/simple_http_parsing/configure
@@ -1,22 +1,58 @@
 #! /bin/sh
 
 #
+# Default settings
+#
+SYSTEM=
+BEOS_NETSERVER=no
+MATH=no
+PTHREAD=no
+OPENSSL=
+GTK=
+PREFIX=/usr/local
+CC="${CC-cc}"
+CFLAGS="${CFLAGS}"
+CXX="${CXX-c++}"
+CXXFLAGS="${CXXFLAGS}"
+LDFLAGS="${LDFLAGS}"
+
+
+#
 # Functions
 #
 usage()
 {
   cat << EOF
 
-  OpenSSL options:
-    --disable-openssl      Disable OpenSSL, use built-in SHA1 implementation
-    --openssl-prefix=PATH  Location of OpenSSL headers and library
-    --disable-gtk          Don't build the GTK+ GUI
+Options:
+  --disable-openssl      Disable OpenSSL, use built-in SHA1 implementation
+  --disable-gtk          Don't build the GTK+ GUI
+  --prefix=PATH          Installation path
 
-  Some influential environment variables:
-    CC          C compiler command (default "cc")
-    CFLAGS      C compiler flags (default "-g -Wall -W")
+Some influential environment variables:
+  CC          C compiler command
+  CFLAGS      C compiler flags
+  CXX         C++ compiler command
+  CXXFLAGS    C++ compiler flags
+  LDFLAGS     linker flags
 
 EOF
+}
+
+cc_test()
+{
+  cat > testconf.c <<EOF
+  int main()
+  {
+    return 0;
+  }
+EOF
+  if ! $CC -o testconf testconf.c > /dev/null 2>&1; then
+    rm -f testconf.c testconf
+    echo "Could not find a working compiler"
+    exit 1
+  fi
+  rm -f testconf.c testconf
 }
 
 openssl_test()
@@ -29,18 +65,78 @@ openssl_test()
       SHA1( 0, 0, 0 );
   }
 EOF
-  if [ -n "$PREFIX" ]; then
-    TMPFLAGS="-I$PREFIX/include -L$PREFIX/lib"
-  fi
-  if $CC $TMPFLAGS -o testconf testconf.c -lcrypto > /dev/null 2>&1
+  if $CC $CFLAGS $LDFLAGS -o testconf testconf.c -lcrypto > /dev/null 2>&1
   then
-    echo "OpenSSL: yes"
-    DEFINES="$DEFINES HAVE_OPENSSL"
-    LINKLIBS="$LINKLIBS -lcrypto"
+    echo "yes"
+    OPENSSL=yes
   else
-    echo "OpenSSL: no, using built-in SHA1 implementation"
+    echo "missing, using built-in SHA1 implementation"
+    OPENSSL=no
   fi
   rm -f testconf.c testconf
+}
+
+lm_test()
+{
+  cat > testconf.c << EOF
+  int main()
+  {
+    return cos( 42 );
+  }
+EOF
+  if ! $CC -o testconf testconf.c > /dev/null 2>&1
+  then
+    if $CC -o testconf testconf.c -lm > /dev/null 2>&1
+    then
+      LDFLAGS="$LDFLAGS -lm"
+    fi
+  fi
+  rm -f testconf.c testconf
+}
+
+lrintf_test()
+{
+  cat > testconf.c << EOF
+  int main()
+  {
+    return ( lrintf( 3.14 ) != 3 );
+  }
+EOF
+  if ( $CC -o testconf testconf.c $LDFLAGS && ./testconf ) > /dev/null 2>&1
+  then
+    CFLAGS="$CFLAGS -DHAVE_LRINTF"
+  fi
+  rm -f testconf.c testconf
+}
+
+gettext_test()
+{
+  cat > testconf.c <<EOF
+  #include <libintl.h>
+  int main()
+  {
+    gettext("");
+  }
+EOF
+
+  if $CC $CFLAGS_GTK $LDFLAGS_GTK -o testconf testconf.c > /dev/null 2>&1
+  then
+    rm -f testconf.c testconf
+    return 0
+  fi
+
+  for intl_testdir in $PREFIX/include \
+      /usr/local/include /usr/X11R6/include /usr/pkg/include
+  do
+    if $CC $CFLAGS_GTK -I$intl_testdir $LDFLAGS_GTK -o testconf testconf.c > /dev/null 2>&1
+    then
+      CFLAGS_GTK="CFLAGS_GTK -I$intl_testdir"
+      rm -f testconf.c testconf
+      return 0
+    fi
+  done
+  rm -f testconf.c testconf
+  return 1
 }
 
 gtk_test()
@@ -58,39 +154,31 @@ gtk_test()
 EOF
       if $CC `pkg-config gtk+-2.0 --cflags --libs` -o testconf testconf.c > /dev/null 2>&1
       then
-        echo "GTK+:    yes"
-        GTK=yes
-        GTKCCFLAGS=`pkg-config gtk+-2.0 --cflags`
-        GTKLINKLIBS=`pkg-config gtk+-2.0 --libs`
+        CFLAGS_GTK=`pkg-config gtk+-2.0 --cflags`
+        LDFLAGS_GTK=`pkg-config gtk+-2.0 --libs`
+        if gettext_test
+        then
+          echo "yes"
+          GTK=yes
+          GTKLOCALEDIR="$PREFIX/share/locale"
+        else
+          echo "no (could not find gettext libintl.h)"
+          GTK=no
+        fi
       else
-        echo "GTK+:    no"
+        echo "no"
         GTK=no
       fi
       rm -f testconf.c testconf
     else
-      echo "GTK+:    no (2.6.0 or later is required)"
+      echo "no (2.6.0 or later is required)"
       GTK=no
     fi
   else
-    echo "GTK+:    no"
+    echo "no"
     GTK=no
   fi
 }
-
-#
-# Defaults settings
-#
-CC="${CC-cc}"
-CFLAGS="${CFLAGS--g -Wall -W}"
-# For > 2 GB files
-DEFINES="_FILE_OFFSET_BITS=64 _LARGEFILE_SOURCE"
-# For asprintf
-DEFINES="$DEFINES _GNU_SOURCE"
-openssl_disable=0
-gtk_disable=0
-GTK=no
-GTKCCFLAGS=
-GTKLINKLIBS=
 
 #
 # Parse options
@@ -100,13 +188,10 @@ while [ $# -ne 0 ]; do
 
   case "x$1" in
     x--disable-openssl)
-      openssl_disable="1";
-      ;;
-    x--openssl-prefix=*)
-      OPENSSL_PREFIX="$param";
+      OPENSSL=no
       ;;
     x--disable-gtk)
-      gtk_disable="1";
+      GTK=no
       ;;
     x--help)
       usage
@@ -122,30 +207,12 @@ done
 SYSTEM=`uname -s`
 case $SYSTEM in
   BeOS)
-    DEFINES="$DEFINES SYS_BEOS"
-
-    CC="gcc"
-    MACHINE=`uname -m`
-    case $MACHINE in
-      BePC) # BeOS on x86
-    	CPU="x86"
-    	;;
-      *)
-        CPU="ppc"
-        ;;
-    esac
-    SYSTEM="$SYSTEM / $CPU"
-	
     RELEASE=`uname -r`
     case $RELEASE in
       6.0*|5.0.4) # Zeta or R5 / BONE beta 7
-        SYSTEM="$SYSTEM / BONE"
-        LINKLIBS="$LINKLIBS -lbind -lsocket"
         ;;
-      5.0*)      # R5 / net_server
-        SYSTEM="$SYSTEM / net_server"
-        DEFINES="$DEFINES BEOS_NETSERVER"
-        LINKLIBS="$LINKLIBS -lnet"
+      5.0*)       # R5 / net_server
+        BEOS_NETSERVER=yes
         ;;
       *)
         echo "Unsupported BeOS version"
@@ -155,23 +222,23 @@ case $SYSTEM in
     ;;
 
   Darwin)
-    DEFINES="$DEFINES SYS_DARWIN"
-    LINKLIBS="$LINKLIBS -lpthread"
+    # Make sure the Universal SDK is installed
+    if [ ! -d /Developer/SDKs/MacOSX10.4u.sdk ]; then
+      cat << EOF
+You need to install the Universal SDK in order to build Transmission:
+  Get your Xcode CD or package
+  Restart the install
+  When it gets to "Installation Type", select "Customize"
+  Select "Mac OS X 10.4 (Universal) SDL" under "Cross Development"
+  Finish the install.
+EOF
+      exit 1
+    fi
+    PTHREAD=yes
     ;;
 
-  FreeBSD)
-    DEFINES="$DEFINES SYS_FREEBSD"
-    LINKLIBS="$LINKLIBS -pthread -lm"
-    ;;
-
-  NetBSD)
-    DEFINES="$DEFINES SYS_NETBSD"
-    LINKLIBS="$LINKLIBS -lpthread -lm"
-    ;;
-
-  Linux)
-    DEFINES="$DEFINES SYS_LINUX"
-    LINKLIBS="$LINKLIBS -lpthread -lm"
+  FreeBSD|NetBSD|OpenBSD|Linux)
+    PTHREAD=yes
     ;;
 
   *)
@@ -181,62 +248,65 @@ esac
 echo "System:  $SYSTEM"
 
 #
-# Mac OS X check for the Universal SDK
+# First things first, check to see if there's a compiler installed
 #
-if [ $SYSTEM = Darwin -a ! -d /Developer/SDKs/MacOSX10.4u.sdk ]; then
-  echo
-  echo "You need to install the Universal SDK in order to build Transmission:"
-  echo "  Get your Xcode CD or package"
-  echo "  Restart the install"
-  echo "  When it gets to \"Installation Type\", select \"Customize\""
-  echo "  Select \"Mac OS X 10.4 (Universal) SDL\" under \"Cross Development\""
-  echo "  Finish the install."
-  exit 1
-fi
+cc_test
 
 #
 # OpenSSL settings
 #
-if [ ${openssl_disable} = 1 ]; then
-  echo "OpenSSL: no, using built-in SHA1 implementation"
+echo -n "OpenSSL: "
+if [ "$OPENSSL" = no ]; then
+  echo "disabled, using built-in SHA1 implementation"
 else
-    openssl_test
+  openssl_test
+fi 
+
+#
+# GTK+ settings
+#
+echo -n "GTK+:    "
+if [ "$GTK" = no ]; then
+  echo "disabled"
+else
+  gtk_test
+fi
+if [ "$GTK" = yes ]; then
+  rm -f gtk/defines.h
+  cat > gtk/defines.h << EOF
+#ifndef TG_DEFINES_H
+#define TG_DEFINES_H
+#define LOCALEDIR               "$GTKLOCALEDIR"
+#endif
+EOF
 fi
 
 #
-# GTK settings
+# Math functions
 #
-if [ ${gtk_disable} = 1 ]; then
-  echo "GTK+:    no"
-else
-    gtk_test
-fi
+lm_test
+lrintf_test
 
 #
-# Generate config.jam
+# Generate Makefile.config
 #
-rm -f config.jam
-cat > config.jam << EOF
-CC          = $CC ;
-LINK        = $CC ;
-CCFLAGS     = $CFLAGS ;
-DEFINES     = $DEFINES ;
-LINKLIBS    = $LINKLIBS ;
-GTK         = $GTK ;
-GTKCCFLAGS  = $GTKCCFLAGS ;
-GTKLINKLIBS = $GTKLINKLIBS ;
+rm -f Makefile.config
+cat > Makefile.config << EOF
+CONFIGURE_RUN  = yes
+SYSTEM         = $SYSTEM
+BEOS_NETSERVER = $BEOS_NETSERVER
+PTHREAD        = $PTHREAD
+OPENSSL        = $OPENSSL
+GTK            = $GTK
+CC             = $CC
+CFLAGS         = $CFLAGS
+CXX            = $CXX
+CXXFLAGS       = $CXXFLAGS
+LDFLAGS        = $LDFLAGS
+CFLAGS_GTK     = $CFLAGS_GTK
+LDFLAGS_GTK    = $LDFLAGS_GTK
 EOF
-if [ -n "$OPENSSL_PREFIX" ]; then
-cat >> config.jam << EOF
-HDRS       += $OPENSSL_PREFIX/include ;
-LINKFLAGS  += -L$OPENSSL_PREFIX/lib ;
-EOF
-fi
-if [ -n "$CPU" ]; then
-cat >> config.jam << EOF
-CPU        = $CPU ;
-EOF
-fi
 
 echo
-echo "To build Transmission, run 'jam'."
+echo "Now use GNU make to build Transmission."
+echo "It may be called 'make' or 'gmake' depending on your system."
